question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
             "you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament,"
             " you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.",
     "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]

question_data2 = [
{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
 "question": "The song &quot;Megalovania&quot; by Toby Fox made its third appearence in the 2015 RPG &quot;Undertale&quot;.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
 "question": "The game &quot;Battlefield 1&quot; takes place during World War I.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"category": "Politics", "type": "boolean", "difficulty": "easy",
 "question": "Denmark has a monarch.", "correct_answer": "True",
 "incorrect_answers": ["False"]},
{"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
 "question": "You can legally drink alcohol while driving in Mississippi.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
 "question": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"category": "Sports", "type": "boolean", "difficulty": "easy",
 "question": "Roger Federer is a famous soccer player.", "correct_answer": "False",
 "incorrect_answers": ["True"]},
{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
 "question": "In the game Dead by Daylight, the killer Michael Myers is refered to as &quot;The Shape&quot;.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
 "question": "The Windows 7 operating system has six main editions.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"category": "Entertainment: Cartoon & Animations", "type": "boolean",
 "difficulty": "easy",
 "question": "Waylon Smithers from &quot;The Simpsons&quot; was originally black when he first appeared in the series.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
 "question": "The shotgun appears in every numbered Resident Evil game.",
 "correct_answer": "True", "incorrect_answers": ["False"]}]
